# This workflow builds and publishes the lightweight 'app' Docker image.
# It should run very quickly as it uses the pre-built base image.
name: Docker Publish - Application

on:
  push:
    branches: [ "main" ]
    # Only run when scripts or the app Dockerfile change
    paths:
      - 'src/**'
      - 'docker/Dockerfile'
      - 'docker/watch-and-process.sh'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push application Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Point to the main application Dockerfile
          file: ./docker/Dockerfile
          push: true
          # Tag the image with ':latest'
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest