# This workflow builds and publishes the STABLE 'base' Docker image
# which contains the custom-compiled FFmpeg and all system dependencies.
name: Docker Publish - Base

on:
  # This allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # Point to the new Dockerfile for the base image
          file: ./docker/Dockerfile.base
          push: true
          # Tag the image with ':base'
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base